### ISSUE TITLE
Skeletonize_pc can throw an error in Computing Topology step

### ISSUE THREAD

**Issue by davodogster** [umr-amap/aRchi#7]
![image](https://user-images.githubusercontent.com/46079516/165841076-dbfeb47c-301d-4564-a72b-61862bedf4a8.png)

Hi guys, awesome work on the package! Do you know what this error means? I don't get it when I use higher parameter values. Cheers

**Comment by oliviermartin7** [comment]
This issue has been fixed. Please install the beta github version:

install.packages("remotes")
remotes::install_github('umr-amap/aRchi')

**Comment by davodogster** [comment]
> This issue has been fixed. Please install the beta github version:
> 
> install.packages("remotes") remotes::install_github('umr-amap/aRchi')

Hi I installed that version. It's still 2.1.0

I still get a similar error

![image](https://user-images.githubusercontent.com/46079516/168502320-55970e01-75e7-4bd3-b47e-fdd1155f247e.png)

This code works and the point clouds looks good
![image](https://user-images.githubusercontent.com/46079516/168502350-05a366f5-4814-4f49-bdcc-54c2a137b970.png)

![image](https://user-images.githubusercontent.com/46079516/168502399-1e4199da-fe50-44aa-9b8d-1f591583859a.png)


EDIT: similarly,

![image](https://user-images.githubusercontent.com/46079516/168503645-dd6bd5ed-76f5-4590-aed9-713b22df03e8.png)


Regards, Sam

**Comment by davodogster** [comment]
Hi @oliviermartin7 @philippeverley Do you know if this is an easy fix? Cheers, Sam

**Comment by oliviermartin7** [comment]
Hi David,
Would you share the point cloud that returns this error/warning ? In the second case (warning message), do you have a QSM at the end ? Can you display it using plot(Tree_skel) ?

Best,
Olivier

@Blecigne

**Comment by davodogster** [comment]
> Hi David, Would you share the point cloud that returns this error/warning ? In the second case (warning message), do you have a QSM at the end ? Can you display it using plot(Tree_skel) ?
> 
> Best, Olivier
> 
> @Blecigne

Hi @oliviermartin7 Yes the second case does work but the skeleton isn't good enough. I think I need to decrease the params. I can send you the PC. Thanks

**Comment by oliviermartin7** [comment]
Hi Sam,

I cannot reproduce your warning with same parameters you used (second example). See image below. It works perfectly with me
![image](https://user-images.githubusercontent.com/49266666/169819455-b43b77d5-08b8-4ad0-9d23-46c011849ba9.png)

Below is the plot of the skeleton with the radius. Far from perfect but the point cloud quality is not optimal, I suggest you to play with parameters in order to get a better QSM.

![image](https://user-images.githubusercontent.com/49266666/169819566-901ab363-82bc-4917-961c-ba98206aa3a0.png)

Concerning the error with initial parameters I get the same problem. We'll solve this issue in the next version.

Best,

Olivier

**Comment by Blecigne** [comment]
Salut l'ami !

C'est embêtant cette erreur ! Peux-tu m'envoyer les données que j'y jette
un œil ?
Mais vu la qualité de son nuage de pts, je crois qu'il serait mieux
d'utiliser un autre QSM. Celui de aRchi est vraiment fait pour les nuages
de pts de très bonne qualité.

Bon j'ai pas eu le temps de bosser sur le papier. Je commence mon nouveau
job la semaine prochaine, je vais essayer de travailler dessus cette
semaine. Est-ce-que tu aurais un petit moment pour en discuter ?

A+ !

*                             Bastien Lecigne*
Ph.D. - Télédétection et architecture des arbres
Université du Québec à Montréal (UQAM) - Département des sciences
biologiques

Chaire CRSNG / Hydro-Québec sur le contrôle de la croissance des arbres
<http://www.arbresurbains.uqam.ca/>
Institut des Sciences de la Forêt Tempérée <http://isfort.uqo.ca/> (ISFORT)
Centre d'Étude de la Forêt <http://www.cef-cfr.ca/>(CEF)


Le lun. 23 mai 2022 à 08:30, oliviermartin7 ***@***.***> a
écrit :

**Comment by davodogster** [comment]
@oliviermartin7 Thanks team!
